// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oznebfouptcmwwmzkqxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bmViZm91cHRjbXd3bXprcXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjAxODAsImV4cCI6MjA2MDM5NjE4MH0.MV9UdQidtfRIJ7Xd_z4U9nwja7gq4c6Mzmm6fajJ-kI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);